<a href="https://colab.research.google.com/github/LaugeHermansen/02456-deep-learning-with-PyTorch/blob/master/3_Feedforward_PyTorch/3.1-what-is-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[5.6072e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4373, 0.6294, 0.8296],
        [0.8136, 0.2659, 0.1276],
        [0.2156, 0.0455, 0.6575],
        [0.1464, 0.4199, 0.9659],
        [0.5175, 0.8112, 0.6319]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [ ]:
x[1:3] = 2
print(x)

# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [10]:
x1 = torch.Tensor(2,17)
print(x1)


x2 = torch.FloatTensor(3,1)
print(x2)
x3 = torch.LongTensor(5,2,1)
print(x3)
x3[:,:,:] = 7
print(x3)
x4 = torch.zeros(5, dtype = torch.uint8)
print(x4)
x4[1:4] = 1
print(x4)



tensor([[ 5.6284e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  1.8244e-34,  0.0000e+00,  2.1430e-35,
          0.0000e+00, -1.5687e-28],
        [ 4.5720e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor([[1.8391e-34],
        [0.0000e+00],
        [2.3694e-38]])
tensor([[[120745600],
         [        0]],

        [[        0],
         [        0]],

        [[        0],
         [        0]],

        [[        0],
         [        0]],

        [[        0],
         [        0]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
tensor([0, 0, 0, 0, 0], dtype=torch.

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3878, 1.1755, 1.1093],
        [1.5316, 1.0490, 0.6592],
        [0.6246, 0.9563, 1.0926],
        [0.2752, 0.5244, 0.9683],
        [0.7206, 1.2650, 1.3212]])


### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[1.3878, 1.1755, 1.1093],
        [1.5316, 1.0490, 0.6592],
        [0.6246, 0.9563, 1.0926],
        [0.2752, 0.5244, 0.9683],
        [0.7206, 1.2650, 1.3212]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3878, 1.1755, 1.1093],
        [1.5316, 1.0490, 0.6592],
        [0.6246, 0.9563, 1.0926],
        [0.2752, 0.5244, 0.9683],
        [0.7206, 1.2650, 1.3212]])


### 2.4 Addition: in-place

adds `x`to `y`

In [14]:
y.add_(x)
print(y)

tensor([[1.3878, 1.1755, 1.1093],
        [1.5316, 1.0490, 0.6592],
        [0.6246, 0.9563, 1.0926],
        [0.2752, 0.5244, 0.9683],
        [0.7206, 1.2650, 1.3212]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([0.6294, 0.2659, 0.0455, 0.4199, 0.8112])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [23]:
r1 = x*y
r2 = torch.Tensor.mul(x,y)
r3 = y.detach().clone(); r3.mul_(x)


tensor(True) tensor(True) tensor(True)


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [27]:
a.add_(1)
print(a)
print(b)
b[2] = 23
print(a)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]
tensor([ 3.,  3., 23.,  3.,  3.])


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [29]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
